---
title: "consensus ML on LFR"
author: "Fabio Morea"
date: "2023-065-23"
 
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE)
```

```{r load libraries, include=FALSE}
library(igraph)
library(tidyverse)
library(gridExtra)
library(aricode) # NMI 
source('./functions_graph_analysis.R')
```

this is our benchmakrk network

```{r}
load_benchmark_network <- function(mui, path = path, verbose = FALSE) {
    filename = paste0(path, mui, ".gml")
    print(filename)
    g <- read_graph(filename, format = "gml")
    # extract giant component
    #components <- igraph::clusters(g, mode = "weak")
    #g <-induced_subgraph(g, V(g)[components$membership == which.max(components$csize)])
    # set names and weight (ww <- 1.0)
    V(g)$comm_built_in <- V(g)$community
    #V(g)$core <- coreness(g)
    #V(g)$str <- strength(g)
    V(g)$name <- paste0("V" , V(g)$label)
    E(g)$ww <- 1.0
    E(g)$weight <- 1.0

    # print
    if (verbose == TRUE) {
        print(paste0("Loaded benchmark network ", path, mui, ".gml"))
        print(paste("Built-in communities: ", max(V(g)$community)))
        mu <- round( empirical_mu(g), 4)
        print(paste("Empirical mixing parameter", mu))
    } 
    return(g)
}
```



# test with weighted RoC

```{r}
g<-read_graph('./benchmark/ring_of_cliques/ring_of_cliques_4_5_B_C_W.gml', format = 'gml')
comms <- find_communities (g, method = 'ML')
lay <- igraph::layout.graphopt(g)
plot(comms,
     g,
     layput = lay,
     #vertex.label = V(g)$id,
     vertex.size = 20, 
     edge.width = E(g)$w)

g2 <- igraph::permute(g, sample(1:vcount(g), size = vcount(g), replace = FALSE ) )
comms <- find_communities (g2, method = 'ML')
plot(comms,
     g2,
     layput = lay,
     #vertex.label = V(g2)$id,
     vertex.size = 20, 
     edge.width = E(g2)$w)



```

 
 
```{r}
g<-read_graph('./benchmark/ring_of_cliques/ring_of_cliques_4_5_B_C_W.gml', format = 'gml')
E(g)$weight <- E(g)$w

V(g)$comm_built_in <- V(g)$community



comms <- find_communities (g, method = 'ML')
plot(comms,
     g,
     vertex.label = V(g)$id,
     vertex.size = 20, 
     edge.width = E(g)$w)

V(g)$community <- comms$membership
nmi = round(aricode::NMI(as.factor(V(g)$community), as.factor(V(g)$comm_built_in)), 3)
print(paste("NMI: ",nmi))
mu_emp <- round(empirical_mu(g), 4)
print(paste("empirical mu: ", mu_emp))
i=1
g1 <- g
for (i in 1:10) {
  
  print(paste("***", i))
  c_d_results_N <- find_communities_N_times (g1,
                                             n_trials = 10,
                                             methods = 'ML')
  print(paste("Number of communities", max(c_d_results_N[1, ])))
  co_occ_matrix <-  normalized_co_occurrence(t(c_d_results_N))
  diag(co_occ_matrix) <- 0
  g1 <- as.undirected(graph_from_adjacency_matrix(co_occ_matrix))
  V(g1)$id <- V(g)$id
  comms <- find_communities (g1, method = 'ML')
  plot(comms,
     g,
     vertex.label = V(g)$id,
     vertex.size = 20, 
     edge.width = E(g)$w)
  V(g1)$community <- comms$membership
  nmi = round(aricode::NMI(as.factor(V(g1)$community), as.factor(V(g)$comm_built_in)), 3)
  print(paste("NMI: ",nmi))
  mu_emp <- round(empirical_mu(g1), 4)
  print(paste("empirical mu: ", mu_emp))
  
  
}
 
```
 
```{r}
met = 'LV'
path <- "./benchmark/LFR/LFR_benchmark_"
g <- load_benchmark_network(mui = 30, path = path, verbose = TRUE)
comm_built_in <- as.factor(V(g)$comm_built_in)

## find communities single trial
comms_1 <- find_communities (g, method = met)
nmi_1 = aricode::NMI(as.factor(comms_1$membership), comm_built_in)
print(paste("NMI single trial : ",nmi_1))


## find communities CONSENSUS gamma_lim
gamma_lim = 0.6
membership_matrix <- find_communities_N_times (g,
    n_trials = 10,
    methods = met)
   
cons_communities <- consensus(t(membership_matrix), method = 'met',gamma_lim = gamma_lim)
results <- analyse_communities(g, cons_communities, verbose = TRUE)
nmi = aricode::NMI(as.factor(cons_communities$membership), comm_built_in)
print(paste("NMI consensus gammalim = ", gamma_lim," : ",nmi))

i=1
g1 <- g
for (i in 1:2) {
  
  print(paste("***", i))
  c_d_results_N <- find_communities_N_times (g1,
                                             n_trials = 20,
                                             methods = met)
  print(paste("Number of communities", max(c_d_results_N[1, ])))
  
  co_occ_matrix <-  normalized_co_occurrence(t(c_d_results_N))
  diag(co_occ_matrix) <- 0
  g1 <- as.undirected(graph_from_adjacency_matrix(co_occ_matrix))
   
  comms <- find_communities (g1, method = met)
   
  V(g1)$community <- comms$membership
  nmi = round(aricode::NMI(as.factor(V(g1)$community), comm_built_in), 4)

 hist(table(V(g1)$community))
  print(nmi)
}

 
```
# compare for all values of MU

 


```{r}
path <- "./benchmark/LFR/LFR_benchmark_"
mui = seq(5,60,5)
method_base = 'LV'
gamma_lim = 0.75

n_trials = 100

summary_n_trials_cons <- data.frame()
nc_builtin <- c()

for (mu in mui) {
  j<-0
  method <- paste0(method_base, '_grp02')

  print(paste('-', mu, method))
  g <- load_benchmark_network(mui = mu,path = path, verbose = FALSE)
  comm_built_in <- V(g)$comm_built_in
  nc_builtin <- max(comm_built_in)
  
  membership_matrix <- find_communities_N_times (g,
    n_trials = n_trials,
    methods = substr(method,1,2))
  for (i in 1:n_trials){
    membs <- as.numeric(membership_matrix[i,])
    nmi = round(aricode::NMI(as.factor(membs),as.factor(comm_built_in)), 3)
    nc_norm <-round(length(table(membs)) / nc_builtin, 4)
    met <- paste0(method, '_ST')
    summary_n_trials_cons <-rbind(summary_n_trials_cons, data.frame(mu, met, j, nmi, nc_norm))
  }

  
  ## CONSENSUS GAMMALIM
  method <- paste0(method_base, '_cons_gamma_LIM')
  print( method)
  cons_communities_1 <- consensus(t(membership_matrix), gamma_lim = gamma_lim )
  cons_communities_1$membership[ cons_communities_1$gamma < gamma_lim ] <-0

  nmi = round(aricode::NMI(as.factor(cons_communities_1$membership), as.factor(comm_built_in)), 3)
  nc_norm <- round(length(table(cons_communities_1$membership)) / nc_builtin,4)
  met <- method
  summary_n_trials_cons <- rbind(summary_n_trials_cons, data.frame(mu, met, j, nmi, nc_norm) )
  print(paste(nmi, nc_norm))
  
   ## CONSENSUS LF repeated
   ## 
  method <- paste0(method_base, '_cons_LF')
  print( method)
  j = 1
  while (j <= 10) {
    co_occ_matrix <-  normalized_co_occurrence(t(membership_matrix))
    
    # all entries of co occurrenc ematrix below a threshold are set to zero  
    co_occ_matrix[ co_occ_matrix < gamma_lim ] <- 0
    
    g_2 <- graph_from_adjacency_matrix(co_occ_matrix, diag = FALSE, weighted=TRUE, mode="upper")
    print(table(E(g_2)$weight))
    hist(E(g_2)$weight)
    
    
    V(g_2)$id <- V(g)$id

    cons_communities_2 <- cluster_louvain(g_2, resolution = 1.0)
    
    nmi = round(aricode::NMI(as.factor(cons_communities_2$membership),as.factor(comm_built_in)), 3)
    nc_norm <-round(length(table(cons_communities_2$membership)) / nc_builtin, 4)
    met <- method
    summary_n_trials_cons <-rbind(summary_n_trials_cons, data.frame(mu, met, j, nmi, nc_norm))
    
    membership_matrix  <- find_communities_N_times (g_2,
    n_trials = n_trials,
    methods = substr(method,1,2))
    
    if (length(table(E(g_2)$weight)) == 1){ break } # reached consensus

    
    j <- j+1
    print(paste(j, nmi, nc_norm))
    
    
  }
}
summary_n_trials_cons %>% write_csv('results_cons_LF_gammalim075.csv')
 
```


```{r}
ggplot(data = summary_n_trials_cons, aes(x = mu, y = nmi, color = met))+
  geom_point()+geom_smooth(se = F, formula = y ~ poly(x, 3))+theme_light()
```



```{r}
ggplot(data = summary_n_trials_cons, aes(x = mu, y = nc_norm, color = met))+
  geom_point()+geom_smooth(se = F, formula = y ~ poly(x, 3))+theme_light()
```

