---
title: "variablity on R of Cliques"
author: "Fabio Morea"
date: "2023-065-23"
 
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE)
```

```{r load libraries, include=FALSE}
library(igraph)
library(tidyverse)
library(gridExtra)
library(aricode) # NMI 
library(rjson)
library(jsonlite)
source('./functions_graph_analysis.R')
path <- "./benchmark/LFR/LFR_benchmark_"

```

# function
```{r}
load_benchmark_network <- function(mui, path = path, verbose = FALSE) {
    #upload graph
    filename = paste0(path, mui, ".gml")
    print(filename)
    g <- read_graph(filename, format = "gml")
    # extract giant component
    #components <- igraph::clusters(g, mode = "weak")
    #g <-induced_subgraph(g, V(g)[components$membership == which.max(components$csize)])
    # set names and weight (ww <- 1.0)
    
    V(g)$core <- coreness(g)
    V(g)$str <- strength(g)
    V(g)$name <- paste0("V" , V(g)$label)
    E(g)$ww <- 1.0
    # print
    if (verbose == TRUE) {
        print(paste0("Loaded benchmark network ", path, mui, ".gml"))
        print(paste("Giant component size :", length(V(g)$community)))
        print(paste("Built-in communities: ", max(V(g)$community)))
        mod <- round( modularity(g, array(V(g)$community+1) ), digits = 4)
        print(paste("Modularity of built-in communities: ", mod))
        mu <- round( empirical_mu(g), 4)
        print(paste("Empirical mixing parameter", mu))
    } 
    return(g)
}
```

 
```{r}
consensus_from_file <-
  function(mu_values, gamma_lim, group_outliers = FALSE) {
    j <- 1
    dfresults <- tibble(mu = numeric(),
                        trial = numeric(), 
                        method = character(),
                        membership = list(),
                        gamma = list()) %>% head(0)
    if (group_outliers) {
      group_out <- "_G"
    } else {
      group_out <- ""
    }
    
    for (mu in mu_values) {
      summary_results_cons <- data.frame()
      membership_cons <- data.frame()
      print(mu)
      g <- load_benchmark_network(mui = mu,
                                  path = path,
                                  verbose = FALSE)
      summary_results <-
        read_csv(paste0('results/summary_single_', mu, '.csv'),
                 show_col_types = FALSE)
      summary_results$method <-
        paste0(summary_results$method, '_cons_', gamma_lim)
      membership_matrix <-
        read_csv(paste0('results/matrix_single_', mu, '.csv'),
                 show_col_types = FALSE)
      
      for (met in unique(summary_results$method)) {
        print(met)
        selected_rows <- (summary_results$method == met)
        cons_communities <-consensus(t(membership_matrix[selected_rows, ]), gamma_lim = gamma_lim)
        cons_communities$algorithm <- met
        if (group_outliers) {
          cons_communities$membership[cons_communities$gamma < gamma_lim] <- 0
        }
        results <-  analyse_communities(g, cons_communities, verbose = FALSE)
        results$mu_nominal <- mu / 100
        summary_results_cons <-
          rbind(summary_results_cons, results)
        
         dfresults[j, ] <- list(
           mu = mu, 
           trial = i, 
          method = met,
          membership = list(cons_communities$membership),
          gamma = list(cons_communities$gamma)) 
        j <- j + 1
        
        
      }
      file_summary <-
        paste0('results/summary_cons_', mu, '_', gamma_lim, '.csv')
      print(paste('writing ' , file_summary))
      summary_results_cons %>% write.csv(file_summary)
      file_results <-        paste0('results/results_cons_', mu, '_', gamma_lim, '.csv')
      
      
      
    }
    json_data <- toJSON(dfresults)
    write(json_data, file = paste0('results/results_cons_', gamma_lim, '.json'))
    print("Completed.")
    
  }

 
```

# 1 incorporate (LP, gmin = 0.2)

```{r}
mu_values = seq(5, 60, 5)
gamma_lim = 0.2
```


```{r}
gamma_lim = 0.2
consensus_from_file(
    mu_values = mu_values, 
    gamma_lim = gamma_lim , 
    group_outliers = FALSE)
    
```

 
 



```{r}
mu_values = seq(5, 60, 5)
gamma_lim = 0.2
data_to_plot <- data.frame()
for (mu in mu_values) {
    print(mu)
    data_to_plot <- rbind(data_to_plot,
      read_csv(paste0('results/summary_cons_', mu, '_',gamma_lim,'.csv'), show_col_types = FALSE))
}



p1 <- data_to_plot %>% 
  group_by(method, mu_nominal) %>% 
  summarise(mean_nmi = mean(nmi), sd_nmi = sd(nmi) ) %>%
    ggplot(aes(x = mu_nominal, y = mean_nmi)) +
  #geom_rect( aes(NULL, NULL, xmin = .50, xmax = .80, ymin = 0, ymax = 1 ), fill = "lightyellow", alpha = 0.1)+
  geom_line(aes(color = method)) +
  geom_point(aes(color = method)) +
  geom_linerange(aes(ymin =mean_nmi-2*sd_nmi, ymax = mean_nmi + 2*sd_nmi, color = method), linewidth = 2, alpha = 0.5)+
  geom_hline(yintercept = 0.5)+geom_hline(yintercept = 1)+geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0.5, color = 'red')+
  labs(title = "Normalized Mutual Information ", y = "NMI", x = "empirical mixing parameter") +
  theme_light()   
 
 
p2 <- data_to_plot %>% 
  group_by(method, as.factor(mu_nominal)) %>%  
  ggplot(aes(x = mu_nominal, y = nc_norm)) +
  geom_line(aes(color = method)) +
  geom_point(aes(color = method)) +
  geom_hline(yintercept = 0.5) +
  geom_vline(xintercept = 0.5, color = 'red')+
  labs(title = "number of communities ", y = "normalized number of communities C/C0", x = "empirical mixing parameter") +
  theme_light()   

grid.arrange(p1, p2, ncol = 2)

```


```{r}
data_to_plot %>%
    select(mu_nominal, mu_emp, mu_built_in) %>%
    ggplot(aes(x = mu_built_in, y = mu_emp)) +
    geom_abline(coef=c(0,1))+
    geom_point(aes(color = as.factor(mu_nominal))) +
    xlim(0,1)+ylim(0,1)+
    
    theme_light()   
```

  
## 2 highlight (LP, gmin = 0.9)

```{r}
gamma_lim = 0.9
consensus_from_file(
    mu_values = mu_values, 
    gamma_lim = gamma_lim, 
    group_outliers = FALSE)
    
```

 
```{r}
mu_values = seq(5, 60, 5)
gamma_lim = 0.9
data_to_plot <- data.frame()
for (mu in mu_values) {
    print(mu)
    data_to_plot <- rbind(data_to_plot,
      read_csv(paste0('results/summary_cons_', mu, '_',gamma_lim,'.csv'), show_col_types = FALSE))
}
 

```

## 3 group (LP, gmin = 0.9 and group)


```{r}
gamma_lim = 0.9
consensus_from_file(
    mu_values = mu_values, 
    gamma_lim = gamma_lim, 
    group_outliers = TRUE)
    
```

 
```{r}
data_to_plot <- data.frame()
for (mu in mu_values) {
    print(mu)
    data_to_plot <- rbind(data_to_plot,
      read_csv(paste0('results/summary_cons_', mu, '_',gamma_lim,'_G.csv'), show_col_types = FALSE))
}
 
```
 
# final plot
grid.arrange(p1, p4, p2, p5, p3, p6, ncol = 2, nrow = 3)

```{r}
#load data from single trials
summary_results <- data.frame()
membership_matrix <- c()
for (mu in mu_values) {
    summary_results <-
        rbind(summary_results, 
              read_csv(paste0('results/summary_single_', mu, '.csv')))
 
}

data_to_plot1 <- rbind(data_to_plot%>% select(colnames(summary_results)), summary_results) 
```

 
# PLOT

```{r echo=FALSE, message=FALSE, warning=FALSE}
json_data <- fromJSON('results/results_cons_0.2.json')
cols_to_extract <- c('method', 'trial', 'mu')
tmp_list <- list()
nn <- length(cols_to_extract)
for (i in 1:nn){
    tmp_list[[i]] <- pluck(json_data, cols_to_extract[i]) 
}
df <- data.frame(tmp_list)
names(df) <- cols_to_extract
gammas <-   pluck(json_data, "gamma")
membs  <-   pluck(json_data, "membership")

n_trials = length(gammas)
n_nodes <- 1000
# extract gamma, which is a list of 1000 
for (i in 1:n_trials){ 
  df$gamma[i] <- list(gammas[[i]]) 
  #df$membs[i] <- list(membs[[i]]) 
  } 

# tidy dataset ready for plotting distribution of gammas
df2 <- df %>%
    unnest(gamma) %>%
    pivot_longer(cols = c(gamma), names_to = 'tmp', values_to = 'gamma')  %>% 
    select(-tmp) %>%  
    arrange(method) %>%
  mutate (mm = substr(method,1,2))



df2  %>% filter(mu %in% c(5, 25, 55)) %>% filter(mm %in% c('LP', 'ML'))%>%
  ggplot(aes(x = gamma)) +
  facet_grid(cols = vars(method), rows = vars(mu)) +
  xlim(0.7, 1.1) +
  
  #geom_density(adjust = 4,  color = "red") +
  geom_histogram(aes(y = ..density..),
                 position = "identity",
                 alpha = 0.5) +
  labs(title = "distribution of gamma",
       x = "gamma",
       y = "Percentage") 
 
```


```{r}

```

