---
title: "consensus comunity detection"
author: "Fabio Morea"
date: "2023-07"
 
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE)
```

```{r load libraries, include=FALSE}
library(igraph)
library(tidyverse)
library(gridExtra)
library(ggpubr)
library(aricode) # NMI 
source('./functions_graph_analysis.R')
```

load data

```{r}



test_and_plot_variability <- function(g, t, shuffle, methods, resolution) {
  results <- data.frame()
  for (met in methods){
    print(met)
    M <- data.frame(name = V(g)$name)
    mod <- c()
    for (i in 1:t) {
      if (shuffle){
          gs <- igraph::permute(g, sample(1:vcount(g),size = vcount(g),replace = FALSE))  
      } else {
        gs <- g
      }
      comms <-find_communities(gs, method = met, r = resolution)
      comm_labeled <-data.frame(name = V(gs)$name, memb = comms$membership)
      M <-inner_join(M ,  comm_labeled, by = 'name')
      colnames(M) <- c('name', seq(1:i))
      mod[i] <- igraph::modularity(gs,comms$membership)
    }
    M <- M %>% arrange(name) %>% select(-name)
    best_trial = which.max(mod)
    for (i in 1:t){
      mm = mod[i]
        nmi = aricode::NMI(as.factor(M[,i]), as.factor(M[,best_trial]))
        nc = length(table(M[,i]))  
        results <- rbind(results, data.frame(met, mm, nmi, nc))
    }
  }
  
  results <- results %>% mutate(nc = as.integer(nc))
  
  p1<-results%>%
    ggplot() + theme_minimal()+   theme(legend.position="none") +
    xlab("NMI")+ 
    facet_wrap( vars(met), nrow = 5)+#, scales="free")+#ylim(0.6,1)+
    geom_histogram(aes(x = nmi, fill = met, color = met, border = 'white'), bins = 20) 
  
  
  p2<-results%>%
    ggplot() + theme_minimal()+  theme(legend.position="none") +#theme(aspect.ratio = 1) + 
    xlab("# communities")+  scale_x_discrete()+
    facet_wrap( vars(met), nrow = 5)+#, scales="free")+#ylim(25,100)+
    geom_bar(aes(x = as.factor(nc), fill = met,  color = met, border = 'white'))
  
  
  p3<-results%>%
    ggplot() + theme_minimal()+  theme(legend.position="none") +#theme(aspect.ratio = 1) + 
    xlab("# communities")+ scale_x_discrete()+
    ylab("modularity")+ 
    facet_wrap( vars(met), nrow = 5)+#, scales="free")+
    geom_point(aes(y = mm, x = as.factor(nc), color = met) )
  
  ggarrange(p1,p2, p3, ncol = 3)

}
```

```{r}
path <- "./benchmark/LFR/LFR_benchmark_"
g <- load_benchmark_network(mui = 20, path = path, verbose = TRUE)
```



 ```{r}


test_and_plot_variability(g, 
                          t = 100, 
                          shuffle = TRUE, 
                          methods = c('LV', 'LD', 'IM', 'LP', 'WT'), 
                          resolution = c(1.0)) 

 
 ```

```{r}
test_and_plot_variability(g, 
                          t = 100, 
                          shuffle = TRUE, 
                          methods = c('LV', 'LD', 'IM', 'LP', 'WT'), 
                          resolution = c(1.0)) 
```
 

```{r}
test_and_plot_variability(g, 
                          t = 100, 
                          shuffle = TRUE, 
                          methods = c('LD', 'ML', 'FG'), 
                          resolution = c(1.0)) 
```
 
