---
title: "consensus recursive algorithm"
author: "Fabio Morea"
date: "2023-12-15"
 
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE)
```

```{r load libraries, include=FALSE}
library(igraph)
library(tidyverse)
library(gridExtra)
library(aricode) # NMI 
library(CCD) #source('./functions_graph_analysis.R')
```

# Method proposed by LF 2019 
recursively apply method A until results converge
 
```{r}

recursive_consensus <- function(M, threshold , met, t) {
  j = 1
  
  while (j <= 10) {
    co_occ_matrix <-  normalized_co_occurrence((M))
    
    # all entries of co occurrenc ematrix below a threshold are set to zero
    co_occ_matrix[co_occ_matrix < threshold] <- 0
    
    g2 <- graph_from_adjacency_matrix(
        co_occ_matrix,
        diag = FALSE,
        weighted = TRUE,
        mode = "upper"
      )
    
    print(paste("iteration", j))
    print(table(E(g2)$weight))
    
    cons_communities_2 <-find_communities(g2, method = met, verbose = TRUE)
    print("results of cons com 2")
    print(length(cons_communities_2$membership))

    
    if (length(table(E(g2)$weight)) == 1) {
      print("reached consensus")
      print(length(table(E(g2)$weight)))
      print(j)
      return(cons_communities_2)
    } else {
      print("next iteration")
      #print(g2)
    } 
    
    M  <- find_communities_repeated (g2, n_trials = t, method = met)
    
    j <- j + 1
    
    
  }
  print("reached max iterations")
  
}

```

```{r}

load_benchmark_network <- function(mui, path = path, verbose = FALSE) {
    filename = paste0(path, mui, ".gml")
    g <- read_graph(filename, format = "gml")
    
    g<-as.undirected( g , mode = 'each')
    g<-igraph::simplify(g, remove.multiple = TRUE, edge.attr.comb = igraph_opt("sum"))
    
    V(g)$comm_built_in <-  V(g)$community
    V(g)$core <- coreness(g)
    V(g)$str <- strength(g)
    V(g)$name <- paste0("V" , V(g)$label)
    E(g)$w <- 1.0
    E(g)$ww <- 1.0
    E(g)$weight <- 1.0
    
    # print
    if (verbose == TRUE) {
        print(paste0("Loaded benchmark network ", path, mui, ".gml"))
        print(paste("Giant component size :", length(V(g)$community)))
        print(paste("Built-in communities: ", max(V(g)$community)))
        mod <- round( modularity(g, array(V(g)$community+1) ), digits = 4)
        print(paste("Modularity of built-in communities: ", mod))
    } 
    return(g)
}
```


```{r}
mu = 20
path <- "./benchmark/LFR/LFR_benchmark_"

g <- load_benchmark_network(mui = mu,path = path, verbose = TRUE)
em_bi <- empirical_mu(g)
print(paste("Empirical MU of built-in communities", em_bi))
M <- find_communities_repeated(g,
                                   n_trials=10, 
                                   method = "WT",
                                   shuffle = TRUE,
                                   resolution = c(1.0), 
                                   verbose = TRUE)
commsRC <- recursive_consensus (M, 
                     threshold = 0.6, 
                     met='WT', 
                     t=10) 
 

# Use order function to get the indices that sort communities to match original order in g
# 


V(g)$commsRC <- commsRC$membership[ order(match(commsRC$names, V(g)$name)) ]
nmi <- aricode::NMI(as.factor(V(g)$commsRC), as.factor(V(g)$comm_built_in))
print(nmi)
# empirical mu
V(g)$community<- V(g)$commsRC
em_rc <- empirical_mu(g)
print(em_rc/em_bi)


```


```{r}
path <- "./benchmark/LFR/LFR_benchmark_"
mui = seq(5,60,20)
n_trials = 10
p = 0.80
threshold = 0.50
method_base = 'LP'
shuffle = TRUE
```



```{r}

summary_n_trials_cons <- data.frame()
nc_builtin <- c()

for (mu in mui) {
  print(paste("MU = ", mu))
  j<-0

  method <- paste0(method_base, '_ST')
  print( method)
  g <- load_benchmark_network(mui = mu,path = path, verbose = FALSE)
  comm_built_in <- data.frame(name = V(g)$name, label_built_in = V(g)$comm_built_in)
  nc_builtin <- max(comm_built_in$label_built_in)
  
  # single trials
  M <- find_communities_repeated(g,
                                   n_trials=n_trials, 
                                   method = method,
                                   shuffle = shuffle,
                                   resolution = resolution,#for Louvain
                                   verbose = FALSE)

  for (i in 2:n_trials+1){
    membs <- data.frame( name = M[,1], label_single = M[,i])
    membs <- membs %>% merge(comm_built_in, by = 'name')
    nmi = round(aricode::NMI(as.factor(membs$label_single),as.factor(membs$label_built_in)), 3)
    nc_norm <-round(length(table(membs$label_single)) / nc_builtin, 4)
    met <- method
    summary_n_trials_cons <-rbind(summary_n_trials_cons, data.frame(mu, met, j, nmi, nc_norm))
  }


  
  ## CONSENSUS GAMMALIM
  method <- paste0(method_base, '_cons')
  print(method)
  nco <- normalized_co_occurrence(M)
  hist(nco)
    
  CC <- CCD::consensus_communities(nco,p=p)
  
  # make a community object  
  cons_communities_1 <- make_clusters(g, array(as.numeric(CC$cons_comm_label)))
  cons_communities_1$gamma<-CC$gamma

  #group outliers
  #cons_communities_1$membership[ cons_communities_1$gamma > gamma_lim ] <-0
  #
  membs <- data.frame( name = CC$name, label_cons = CC$cons_comm_label)
  membs <- membs %>% merge(comm_built_in, by = 'name')
  nmi = round(aricode::NMI(as.factor(membs$label_cons),as.factor(membs$label_built_in)), 3)
  nc_norm <-round(length(table(membs$label_cons)) / nc_builtin, 4)
  met <- method

  summary_n_trials_cons <- rbind(summary_n_trials_cons, data.frame(mu, met, j, nmi, nc_norm) )
  print(paste(nmi, nc_norm))
  
  ## CONSENSUS LF 
   
  method <- paste0(method_base, '_cons_LF')
  print( method)
  j = 1
  while (j <= 10) {
    co_occ_matrix <-  normalized_co_occurrence((M))
    
    # all entries of co occurrenc ematrix below a threshold are set to zero  
    co_occ_matrix[ co_occ_matrix < threshold ] <- 0
    
    g_2 <- graph_from_adjacency_matrix(co_occ_matrix, diag = FALSE, weighted=TRUE, mode="upper")
    print(table(E(g_2)$weight))
    hist(E(g_2)$weight)
    
    
    V(g_2)$id <- V(g)$id

    CCR <- cluster_louvain(g_2, resolution = 1.0)
    
     membs <- data.frame( name = CCR$name, label_cons = CCR$membership)
     membs <- membs %>% merge(comm_built_in, by = 'name')
     nmi = round(aricode::NMI(as.factor(membs$label_cons),as.factor(membs$label_built_in)), 3)
     nc_norm <-round(length(table(membs$label_cons)) / nc_builtin, 4)
     met <- method
    summary_n_trials_cons <-rbind(summary_n_trials_cons, data.frame(mu, met, j, nmi, nc_norm))
    
    
    
    if (length(table(E(g_2)$weight)) == 1){ break } # reached consensus

    M  <-  find_communities_repeated (g_2,n_trials = t,method ='LV')
    j <- j+1
    print(paste(j, nmi, nc_norm))
    
    
  }
}
summary_n_trials_cons %>% write_csv('results_cons_LF_gammalim0.csv')
 
```


```{r}
ggplot(data = summary_n_trials_cons, aes(x = mu, y = nmi, color = met))+
  geom_point()+
  geom_smooth()+
  theme_light()
```



```{r}
ggplot(data = summary_n_trials_cons, aes(x = mu, y = nc_norm, color = met))+
  geom_point()+
  geom_line()+
  theme_light()
```

